M48
; DRILL file KiCad 10.0.3 date 2026-05-23T21:48:38
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-23T21:48:38+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C1.020
%
G90
G05
T1
X82.5Y-81.92
X82.5Y-92.08
T2
X82.5Y-96.5
X82.5Y-99.04
T3
X90.365Y-82.745
X90.365Y-97.735
M30
